### ISSUE TITLE
Can't find resource for bundle java.util.PropertyResourceBundle scheduled-jobs.get.js

### ISSUE THREAD

**Issue by douglascrp** [AFaust/ootbee-support-tools#11]
I'm testing support tools on a 5.0.d server.
When I try to acces the Scheduled Jobs page, I get the error below:

```
09280001 Wrapped Exception (with status template): 09280202 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js': Can't find resource for bundle java.util.PropertyResourceBundle, key days
<douglascrp> Exception: java.util.MissingResourceException - Can't find resource for bundle java.util.PropertyResourceBundle, key days
```

The stacktrace:

```
2016-10-28 09:59:40,527  ERROR [extensions.webscripts.AbstractRuntime] [http-nio-8080-exec-19] Exception from executeScript - redirecting to status template error: 09280001 Wrapped Exception (with status template): 09280202 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js': Can't find resource for bundle java.util.PropertyResourceBundle, key days
 org.springframework.extensions.webscripts.WebScriptException: 09280001 Wrapped Exception (with status template): 09280202 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js': Can't find resource for bundle java.util.PropertyResourceBundle, key days
    at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1127)
    at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
    at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:482)
    at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:457)
    at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:551)
    at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:619)
    at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:399)
    at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:280)
    at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
    at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
    at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:421)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1074)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1739)
    at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1698)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.alfresco.scripts.ScriptException: 09280202 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js': Can't find resource for bundle java.util.PropertyResourceBundle, key days
    at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:204)
    at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:212)
    at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:174)
    at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:102)
    at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1364)
    at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
    ... 33 more
Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key days
    at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
    at java.util.ResourceBundle.getString(ResourceBundle.java:407)
    at com.cronutils.descriptor.CronDescriptor.describeDayOfMonth(CronDescriptor.java:92)
    at com.cronutils.descriptor.CronDescriptor.describe(CronDescriptor.java:61)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:126)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:225)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:32)
    at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_scheduled_jobs_get_js_111._c_buildScheduledJobsData_8(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js:244)
    at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_scheduled_jobs_get_js_111.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js)
    at org.mozilla.javascript.optimizer.OptRuntime.callName0(OptRuntime.java:74)
    at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_scheduled_jobs_get_js_111._c_script_0(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js:325)
    at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_scheduled_jobs_get_js_111.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
    at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_scheduled_jobs_get_js_111.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js)
    at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_scheduled_jobs_get_js_111.exec(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/scheduled-jobs.get.js)
    at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:502)
    at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:200)
    ... 38 more
```

This only happens when my browser is configured for Portuguese. It works perfectly when configure for English though.

**Comment by AFaust** [comment]
@jgoldhammer Can you check if this can be addressed in the cron-utils library or if we can provide some kind of override I18n to it? I would have assumed they provide their I18n properties in a way that supports standard failover to a default locale (ideally English).
Otherwise we may have to define a whitelist of user locales to allow for transforming CRON expressions and fall back to hardcoded English for all.

**Comment by jgoldhammer** [comment]
I have created a PR.
https://github.com/jmrozanec/cron-utils/pull/127

Just let us wait a few days. If there is no reaction, we can provide a fix in our code.

**Comment by AFaust** [comment]
Looking at the structure of the project it seems we should be able to provide missing files ourselves if they don't react (or temporarily until they provide a new release). We would only need to put them on the root of the classpath.

**Comment by jmrozanec** [comment]
@jgoldhammer @AFaust Thank you for contributing to [cron-utils](https://github.com/jmrozanec/cron-utils). The pull request was accepted and will release a new version with it over the weekend. If you have some case we can use to reproduce the issue in a test, will be most welcome. Thanks!

**Comment by jmrozanec** [comment]
@jgoldhammer @AFaust [Release 5.0.2](https://github.com/jmrozanec/cron-utils/releases/tag/5.0.2) was published with the fix proposed. Upgrading to it, shall solve your issue. Thanks again for contributing the fix!

**Comment by AFaust** [comment]
I updated the dependency to version 5.0.2 and fallback works correctly for all locales that do not have a bundle in the library.

I did notice that special characters are not included correctly (as \uxxxx tokens) in the *.properties files of cron-utils leading to encoding issues when displayed in a UTF-8 web page. I guess we will have to create a couple of new issues and/or pull requests to have that corrected.

**Comment by jmrozanec** [comment]
@AFaust at cron-utils we will be glad to do a release soon after you send the new version.

**Comment by jgoldhammer** [comment]
@AFaust  @jmrozanec 
I have created a PR.
https://github.com/jmrozanec/cron-utils/pull/129

**Comment by douglascrp** [comment]
I tried it again and it is working now.
Thank you.
