### ISSUE TITLE
"Cannot read property "length" from null" -Error when clicking on "Get Transformer Names"

### ISSUE THREAD

**Issue by jgoldhammer** [AFaust/ootbee-support-tools#6]
![image](https://cloud.githubusercontent.com/assets/3872101/19417224/821aeae6-93a7-11e6-8b76-8ea5b5dfc50f.png)

Stacktrace:
```
2016-10-16 13:47:38,805  ERROR [extensions.webscripts.AbstractRuntime] [http-bio-8080-exec-2] Exception from executeScript: 09160004 Wrapped Exception (with status template): 09160012 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js': 09160011 TypeError: Cannot read property "length" from null (classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js#389)
 org.springframework.extensions.webscripts.WebScriptException: 09160004 Wrapped Exception (with status template): 09160012 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js': 09160011 TypeError: Cannot read property "length" from null (classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js#389)
	at org.springframework.extensions.webscripts.AbstractWebScript.createStatusException(AbstractWebScript.java:1138)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:171)
	at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:512)
	at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:464)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:587)
	at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:656)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScriptInternal(RepositoryContainer.java:428)
	at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:308)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:399)
	at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:210)
	at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:312)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.alfresco.scripts.ScriptException: 09160012 Failed to execute script 'classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js': 09160011 TypeError: Cannot read property "length" from null (classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js#389)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:211)
	at org.alfresco.repo.processor.ScriptServiceImpl.execute(ScriptServiceImpl.java:219)
	at org.alfresco.repo.processor.ScriptServiceImpl.executeScript(ScriptServiceImpl.java:181)
	at org.alfresco.repo.web.scripts.RepositoryScriptProcessor.executeScript(RepositoryScriptProcessor.java:109)
	at org.springframework.extensions.webscripts.AbstractWebScript.executeScript(AbstractWebScript.java:1376)
	at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:86)
	... 32 more
Caused by: org.alfresco.error.AlfrescoRuntimeException: 09160011 TypeError: Cannot read property "length" from null (classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js#389)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:533)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.execute(RhinoScriptProcessor.java:207)
	... 37 more
Caused by: org.mozilla.javascript.EcmaError: TypeError: Cannot read property "length" from null (classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js#389)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3687)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3665)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3693)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3712)
	at org.mozilla.javascript.ScriptRuntime.undefReadError(ScriptRuntime.java:3725)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1483)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_test_transform_details_get_js_21._c_getTransformerNames_17(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js:389)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_test_transform_details_get_js_21.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js)
	at org.mozilla.javascript.optimizer.OptRuntime.call0(OptRuntime.java:23)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_test_transform_details_get_js_21._c_script_0(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js:660)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_test_transform_details_get_js_21.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:394)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3091)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_test_transform_details_get_js_21.call(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js)
	at org.mozilla.javascript.gen.classpath__alfresco_templates_webscripts_org_orderofthebee_ootbee_support_tools_admin_support_tools_test_transform_details_get_js_21.exec(classpath*:alfresco/templates/webscripts/org/orderofthebee/ootbee-support-tools/admin/support-tools/test-transform-details.get.js)
	at org.alfresco.repo.jscript.RhinoScriptProcessor.executeScriptImpl(RhinoScriptProcessor.java:509)
	... 38 more
```

**Comment by mrksjs** [comment]
there was a typo in a model var name, it is fixed now. 
I still have to learn how to rebase properly ...
